bpython/curtsiesfrontend/repl.py
=> Add deactivate message when turning off auto-reload

.travis.yml, bpython/curtsiesfrontend/filewatch.py, bpython/curtsiesfrontend/repl.py, bpython/test/test_filewatch.py
Change API of filewatch.py, update curtsies repl to reflect changes. Addresses Bug #435, includes some unit tests but does not cover all the methods.
=> Refactor filewatching and add tests.

doc/sphinx/source/configuration.rst
Simplifies documentation for setting up a custom config file.
=> Clean up documentation and address issue #404

bpython/autocomplete.py, bpython/test/test_autocomplete.py
One of the test is failing due to #455
=> Add tests for dictionary key completion

bpython/autocomplete.py, bpython/test/test_autocomplete.py
Resolves: https://github.com/bpython/bpython/issues/480
=> Old style class dict autocomplete

bpython/history.py, bpython/patch_linecache.py, bpython/repl.py, bpython/test/test_interpreter.py
- Patches the linecache module to achieve this
- inspect.getsource() works for functions defined on the console
- tracebacks show code for frames inside interactively defined functions
fixes bpython/bpython#229
=> Remember the source of interactively defined functions

bpython/args.py
Added code Tom suggested at https://github.com/bpython/bpython/issues/506
=> fixed bug #506

bpython/test/test_curtsies_repl.py
#549 for prevent same mistake. 
also enable Auto-Reloading(F5) and rewind(C-R) once, imported module was NOT re-import. I couldn't figure it out why.
=> add test for #549

bpython/curtsiesfrontend/manual_readline.py, bpython/test/test_manual_readline.py
https://github.com/bpython/bpython/issues/548
=> Fix bug #548 - Transpose when empty line crashes

LICENSE, bpython/autocomplete.py, bpython/curtsies.py, bpython/curtsiesfrontend/repl.py, bpython/line.py, bpython/repl.py, bpython/simpleeval.py, bpython/simplerepl.py, bpython/test/test_autocomplete.py, bpython/test/test_curtsies_painting.py, bpython/test/test_curtsies_repl.py, bpython/test/test_line_properties.py, bpython/test/test_repl.py, bpython/test/test_simpleeval.py
I wasn't sure how I felt about this before, but inheriting and overriding methods seems nicer than passing in a bunch of callbacks to the constructor of the Repl object.
=> Inheritance over composition

doc/sphinx/source/contributing.rst
This pull request fixes a typo.
=> spelling: Remember

bpython/urwid.py
Fixes #672 
I played around with writing urwid tests a bit then just fixed the issue - so makes some untested code work better probably :/
=> fix default values of keyword only arguments

bpython/curtsiesfrontend/repl.py
I tried something a little different but it's been so long since I last looked at it I didn't want to merge it right away.
=> Changes to PeriGK's ctrl-o PR

doc/sphinx/source/contributing.rst
"Next install the install your..." wasn't making sense.
=> Correct "next" duplication in line 40

bpdb/debugger.py
=> don't ignore rc flines by by overwriting rcLines

bpython/curtsiesfrontend/repl.py
=> Fix newline handling in stdout and stderr

bpython/config.py, bpython/curtsiesfrontend/repl.py, bpython/sample-config
This is something I personally would love to have on by default and I'm sure others feel the same way. No harm in adding it as an option.
=> Add default_autoreload config option

bpython/curtsiesfrontend/coderunner.py
Follow on to https://github.com/bpython/bpython/pull/679
Allows code to be run not in the main thread
=> simple fix (ctrl-c handling probably doesn't work in all cases)

bpython/repl.py
Fixes https://github.com/bpython/bpython/issues/710
=> Fix NameError when saving to a file

bpython/test/test_args.py, bpython/test/test_config.py, bpython/test/test_curtsies_parser.py, bpython/test/test_curtsies_repl.py, bpython/test/test_interpreter.py, bpython/test/test_manual_readline.py, bpython/test/test_simpleeval.py
This annoyed me while debugging #712.
=> use self.assertEqual instead of self.assertEquals (deprecated)

bpdb/debugger.py
resolves https://github.com/bpython/bpython/issues/713
I've been using this edit locally and it seems to be doing the job.
=> expose global vars in debugger

bpython/curtsiesfrontend/repl.py
=> remove debugging print in rev incr search

bpython/curtsiesfrontend/replpainter.py
Fix #767 by calling FSArray constructor instead of fsarray convenience function
=> Fix 767 by using correct function

bpython/filelock.py
I divided the changes from #781 into two branches. This is the simple fix that I kept in `master`.
=> Close lock file using os.close()

bpython/test/test_autocomplete.py
=> Fix simple typo: atempt -> attempt

CHANGELOG, bpython/cli.py, bpython/curtsies.py, bpython/translations/bpython.pot, bpython/translations/de/LC_MESSAGES/bpython.po, bpython/translations/es_ES/LC_MESSAGES/bpython.po, bpython/translations/fr_FR/LC_MESSAGES/bpython.po, bpython/translations/it_IT/LC_MESSAGES/bpython.po, bpython/translations/nl_NL/LC_MESSAGES/bpython.po, bpython/urwid.py
@sebastinas can you take a look at mostly the texts here?
=> Show deprecation warnings for urwid/curses/python2.

bpython/curtsiesfrontend/coderunner.py, bpython/curtsiesfrontend/repl.py
=> Remove unused imports

CHANGELOG, bpython/config.py, bpython/paste.py, bpython/repl.py, doc/sphinx/source/configuration-options.rst
Implement the new pinnwand API.
=> Pinnwand api v1

bpython/repl.py
=> Remove Enum to maintain Python 2 support

bpython/curtsiesfrontend/repl.py, bpython/repl.py
=> Restore original save behavior for cli and urwid

.github/workflows/lint.yaml
% ___codespell --ignore-words-list="ba,te" --quiet-level=2 --skip="*.po"___
```
./README.rst:69: priviledge ==> privilege
./README.rst:111: pacakge ==> package
./CHANGELOG.rst:776: perseverence ==> perseverance
./bpython/sample-config:40: pallete ==> palette
./bpython/cli.py:527: srings ==> strings
./bpython/curtsiesfrontend/interaction.py:60: Messsage ==> Message
./bpython/test/test_manual_readline.py:143: deltion ==> deletion
./doc/sphinx/source/django.rst:15: enviroment ==> environment
./doc/sphinx/source/django.rst:16: enviroment ==> environment
./doc/sphinx/source/django.rst:23: enviroment ==> environment
./doc/sphinx/source/man-bpython.rst:22: Hilights ==> Highlights
./doc/sphinx/source/configuration-options.rst:405: cutted ==> cut
```
https://github.com/codespell-project/codespell
=> GitHub Actions: Find typos with codespell

bpython/args.py
Fixes #841 while keeping the behaviour of #692 and #506.
Thanks!
=> Respect locals when using embed()

README.rst
A bit of editing to move closer to standard U.S. English grammar & conventions. (Also, wrapping some terms in backticks for clarity & consistency.)
=> Grammatical & formatting improvements: README.rst

bpython/curtsiesfrontend/repl.py
Issue: https://github.com/bpython/bpython/issues/913
=> Fixing error when editing session with external editor

bpython/line.py, bpython/test/test_line_properties.py
=> Changed dict key-matching regex to capture any valid dict key

bpython/autocomplete.py
We're not checking these in CI nor are we providing a config file yet.
I used mypy 0.910 run directly on bpython/autocomplete.py and still had 3 errors after these changes.
=> Mypy types for completion

bpython/importcompletion.py
When I run bpython from my home directory it
1. takes minutes to work through all of the directories accessible from there to find all potentially importable Python modules, and
2. is occasionally unresponsive for seconds at a time while working through portions of the tree that don't have any modules.
This PR addresses 2. without doing anything about 1, (which hides it a bit) by yielding more frequently to avoid these interruptions.
1. happens because import completion is working through directories without an `__init__.py` file because one isn't required anymore. There is a list of locations to ignore, if I want to fix that I should look at that.
=> Yield reliably from import module discovery coroutine

bpython/curtsiesfrontend/repl.py
Issue: https://github.com/bpython/bpython/issues/955
- Reproducing sys.stdin.readline behavior for size parameter.
=> Allowing sys.stind.readline receive size parameter

bpython/curtsiesfrontend/repl.py, bpython/repl.py
This addresses https://github.com/bpython/bpython/issues/979
=> Add more keywords to trigger auto-deindent

setup.cfg
hi! this url appears to be a typo.
=> Fix URL typo in package metadata

.github/workflows/lint.yaml, bpython/_typing_compat.py, bpython/curtsiesfrontend/repl.py, bpython/pager.py, bpython/repl.py, bpython/test/test_preprocess.py, setup.cfg
(Need to run this on CI to make sure it worked)
=> Fix linters
