- bpython/config.py
- bpython/curtsiesfrontend/manual_readline.py
This changes the logic for the function `get_key_no_doublebind()` and removes the mutable list which was previously used to keep track of keybindings which were already assigned. Although this fix passes the test cases and the specific case mentioned in #447, the logic is such that specifying the same custom keybinding for two commands will result in only one command being bound. Also I am getting 12 skipped tests when running nosetests, any ideas why this is happening?
With:
`help = F9`
`show_source = F9`
F9  is mapped to `show_source` and `help` is not mapped to any key. I think this is because the keybindings are assigned sequentially so because `show_source` is assigned first (line 182) vs `help` (line 210).
I think this is still a substantial improvement over the old code because it …
> Refactor and fix keybinding issue (fixes #447)

- bpython/test/test_autocomplete.py
I added a test for param completion. However I can't get function param to ever be suggested in bpython. I am looking into this.
> Add test for param completion

- bpython/curtsiesfrontend/repl.py
This PR adds Ctrl-e to select the current suggestion in the curtsies frontend.
I love how the curtsies front-end shows completions from the history as I type. In order to complete that current suggestion I have to press 'Right-Arrow' or 'Ctrl-f'. I presume this is inspired by fish shell. Fish shell also allows Ctrl-e to select the current suggestion and this PR adds that behavior to bpython.
> Add Ctrl-e to complete current suggestion.

- bpython/autocomplete.py
- bpython/curtsiesfrontend/replpainter.py
- bpython/inspection.py
- bpython/repl.py
Introduced three namedtuples along with associated refactoring
LinePart - Representing a word and its location in the interpreter input
FuncProps - Replaces the current argspec which contained function specific info along with Arg info. 
Argspec - Newly defined Argspec representing python2 and python3 argspec result from the inspect.getargspec()
> Refactoring named tuple

- bpython/curtsiesfrontend/repl.py
2 issues.
+ sys.modules.keys() return [Dictionary view objects](https://docs.python.org/3/library/stdtypes.html#dictionary-view-objects). it referencing sys.modules(not copy of key).
+ we can't delete sys.module[modname], while iterating it self. see: http://ideone.com/ayHDZS
> Reload and Auto-reloading doesn't work when using Python3.x

- bpython/curtsiesfrontend/manual_readline.py
- bpython/test/test_manual_readline.py
Transpose (Ctrl+t) correctly mimics emacs's transpose behavior.
> Transpose characters if cursor is at the end of the line

- bpython/autocomplete.py
- bpython/test/test_autocomplete.py
This change will require you to write two underscores in order to get autocompletion of attributes starting with two underscores, as requested in #528.
I'm not too sure about the changes to the tests, and if there should be some tests for this filtering as well. I just tried to make the change as minimal as possible while making the tests pass.
> Filter out two underscore attributes in auto completion

- bpython/cli.py
Something I bumped into getting bpython on windows. Python 3 doesn't allow addition of dict_items and list in make_colors if OS is windows, but union works!
> Fix small python 3 compatibility issue using windows

- bpython/inspection.py
- bpython/repl.py
- bpython/test/test_repl.py
```
>>> import blessed
>>> blessed.sequences.Sequence(
┌────────────────────────────────────────────────────────────┐
│ blessed.sequences.Sequence: (cls, sequence_text, term)     │
│ Sequence                                                   │
│ SequenceTextWrapper                                        │
│ Class constructor.                                         │
│                                                            │
│ :arg sequence_text: A string that may contain sequences.   │
│ :arg blessed.Terminal term: :class:`~.Terminal` instance.  │
└────────────────────────────────────────────────────────────┘
```
> Show __new__ docstrings. Fixes #572

- bpython/autocomplete.py
- bpython/test/test_autocomplete.py
- bpython/test/test_repl.py
I found parameter name completion wasn't working. I don't know if it's ever worked. Now this happens:
bpython version 0.15.dev177 on top of Python 2.7.10 /Users/tomb/.virtualenvs/bpython/bin/python2.7
>>> def foo(abc=1, abd=2, xyz=3):
...     "function with keyword parameters"
...
>>> foo(ab
┌──────────────────────────────────────────────────┐
│ foo: (abc=1, abd=2, xyz=3)                       │
│ abc= abd= abs(                                   │
│ function with keyword parameters                 │
└──────────────────────────────────────────────────┘
> fix parameter name completion

- bpython/test/test_curtsies_repl.py
Possibly we should have a test that explicitly tests for this behavior, but with our current tests I got failures only when tests were run in a specific order.
> fix run order-dependant test failure

- bpython/curtsies.py
- bpython/curtsiesfrontend/repl.py
- bpython/test/test_curtsies.py
- bpython/test/test_curtsies_repl.py
This switches from using curtsies-created paste events to creating paste events in bpython whenever 10  or more keypress events are queued up.
I think long term this is a good move because it's one less Curtsies-specific piece of input functionality, and I'd like to remove this feature from Curtsies and use Blessed for input code eventually because I trust @jquast to get it right more than I do myself. It's also better because now it helps the UI catch up any time it gets behind on events, e.g. from a fast typist on a slow machine, whereas before the bytes had to be read in the same system call to be considered a paste event. The paste threshold of 10 should be tuned for this, it should probably be much lower (2 or 3?).
If you don't like the `combined_events` coroutine I'd be happy to …
> Paste detection in bpython instead of Curtsies, fixes #575

- LICENSE
- bpython/autocomplete.py
- bpython/line.py
- bpython/repl.py
- bpython/simpleeval.py
- bpython/test/test_autocomplete.py
- bpython/test/test_curtsies_repl.py
- bpython/test/test_line_properties.py
- bpython/test/test_repl.py
- bpython/test/test_simpleeval.py
This implements the feature initially described in issue #37, autocompletion of literals, and includes autocompletion of literals as discussed later in the thread.
This implementation is relatively conservative: it will only evaluate lists, tuples, strs, unicodes, dicts. It evaluates no methods called with method call syntax, only `__getitem__` invoked by `[]` on these types.
To find an expression to evaluate before current attribute being completed, ast.parse is called on strings of increasing size - this could be a performance issue.
> Attribute completion on simple expressions

- bpython/repl.py
- bpython/test/test_interpreter.py
Mimicking the default Python interactive interpreter, change stack traces so they no longer list the line number.
> fix #591 changing stack trace linenos

- CHANGELOG
- bpython/inspection.py
- bpython/line.py
- bpython/repl.py
- bpython/simpleeval.py
- bpython/test/test_autocomplete.py
- bpython/test/test_inspection.py
- bpython/test/test_line_properties.py
- bpython/test/test_repl.py
- bpython/test/test_simpleeval.py
Safely do attribute access to provide completion on simple expressions:
```
>>> import ast
>>> m = ast.parse('1 + 1')
>>> m.body[0].value.
┌───────────────────────────────────────────────────
│ col_offset left       lineno     op         right
└───────────────────────────────────────────────────
```
> Simple eval attr access

- bpython/curtsiesfrontend/_internal.py
This should probably be looking at the the source for an encoding message, but I'm worried that by the time pydoc outputs this it's too late to find it.
> require unicode for pager

- bpython/cli.py
It breaks the code when using on windows python2
unsupported operand type | 'list' and 'list': python 2.7
> Fixing Windows Python2 compatibility

- bpython/cli.py
- bpython/curtsiesfrontend/repl.py
File "/usr/lib/python3.5/site-packages/bpython/cli.py", line 977, in p_key
self.statusbar.message(_(e))
File "/usr/lib/python3.5/site-packages/bpython/cli.py", line 1605, in message
self.settext(s)
File "/usr/lib/python3.5/site-packages/bpython/cli.py", line 1655, in settext
if len(s) >= self.w:
TypeError: object of type 'SourceNotFound' has no len()
I have used the same code as with `bpython/curtsiesfrontend/repl.py`.
> Fix TypeError when using F2 without some source

- bpython/curtsiesfrontend/manual_readline.py
curtsies stopped supporting PADDELETE at this point: https://github.com/thomasballinger/curtsies/commit/415016436eb30411acc1a4725aceaab6c00d58c7
fixes #609
> Fix DELETE key not being recognized

- bpython/curtsiesfrontend/coderunner.py
- bpython/curtsiesfrontend/repl.py
Some applications that use curses require that the object in `sys.stdout` be a file with the a method called `fileno`. In order to facilitate this, a `fileno` method was added to the FakeOutput object. An extra named parameter was added to the constructor as well to facilitate choosing the result of the `fileno` method. The default value is `1` (or standard output). 
The two allocations of FakeOutput (for stderr and stdout) were also changed to specify the file number to be returned by `fileno`.
These additions do not effect any existing code, but allow users to import libraries such as pwntools while using bpython.
> Added fileno support to FakeOutput

- bpdb/debugger.py
When using bpdb together with pdb++ [1], using `debug …` will cause a
TypeError, because pdbpp passes in a `Config` kwarg [2].
…/venv/lib/python3.5/site-packages/pdb.py:647: in do_debug
return orig_do_debug(self, arg)
/usr/lib64/python3.5/pdb.py:1090: in do_debug
p = Pdb(self.completekey, self.stdin, self.stdout)
…/venv/lib/python3.5/site-packages/pdb.py:636: in new_pdb_with_config
return self.__class__(*args, **kwds)
E   TypeError: __init__() got an unexpected keyword argument 'Config'
This patch fixes bpdb to accept and pass on any args/kwargs.
For reference, this is the stacktrace when pdb++ gets instantiated:
File "…/venv/lib/python3.5/site-packages/pytestbpdb/ptbpdb.py", line 50, in set_trace
pdb.BPdb().set_trace(frame)
File "…/venv/lib/python3.5/site-packages/bpdb/debugger.py", line …
> bpdb: fix TypeError with pdbpp's `__init__`

- bpython/test/test_interpreter.py
Cherry-picking a commit from the unmergeable #636, just to make test expectations harder to fail unintentionally.
Also, for me to get a commit in bpython Git history. :laughing:
> Update tests expectations

- bpython/curtsiesfrontend/repl.py
- bpython/test/test_curtsies_painting.py
Fix #466 
Try to preserve n lines of history (`try_preserve_history_height`) unless that space is needed to make the completion box m lines (`min_infobox_height`) long (provided there is content to fill it). If there's space in the terminal below the cursor to fill and infobox content to fill ti with, go ahead and fill it.
TODO:
[x] - test desired behavior in each case
[x] - docstring describing this layout technique
> completion box size changes based on terminal size

- bpython/paste.py
Currently bpython will crash calling an external helper, this is because it will try to unpack a tuple of one into `paste_url, removal_url` This simply returns `None` as the removal_url.
> Fix paste helper

- bpython/curtsiesfrontend/replpainter.py
- bpython/test/test_curtsies_painting.py
Boto is doing something pretty weird: in Python 3, it makes it possible to end up with bytestring docstrings. We fix this here by always assuming utf8 in this case. Previously we assumed ascii, and did it implicitly by letting `string.split(u'\n')` turn it into unicode, which was no good.
> fix weird boto docstrings

- data/bpython.appdata.xml
This trivial markup fix ensures that the `<p>` node is closed in the right place, so that when software centers like gnome-software show the appdata, the description section does not get curtailed at the place where the `<ul>` begins.
> Close <p> node in description correctly.

- bpython/curtsiesfrontend/manual_readline.py
`Getargspec` method of `inspect` module was deprecated in py3.
There is `getfullargspec` method but it was deprecated in several py3 versions.
There is no problem if I launch `bpython` itself. But when I launch `bpython` shell from `django` manage command there are a lot of deprecation warning messages.
So I propose to use `signature` method for py3.
> Fix deprecations warnings

- bpython/curtsiesfrontend/replpainter.py
Fixes #670.
May not work with the last curtsies release, tested with the git version.
Although, I'm not sure if converting to FmtStr is the most efficient way of splitting lines, but curtsies.formatstring.width_aware_slice was not working as I've expected.
> Use width aware slice

- bpython/curtsiesfrontend/repl.py
Because [signal.signal][1] is only allowed to be called from the main thread, if you use bpdb in another thread it will crash upon entering the repl.  By ignoring the resulting `ValueError` the show can go on.
This makes bpdb useful in Django's runserver, even with threading and/or live reload on.
A question is what to tell the user when this happens? Just ignore it like here, or log something? What on which level?
Feedback much appreciated.
Closes #555 I think
[1]: https://docs.python.org/3/library/signal.html#signal.signal
> Allow bpython/bpdb outside main thread

- bpython/curtsiesfrontend/manual_readline.py
- bpython/test/test_manual_readline.py
Fixes #655
Just needed a slight tweak to the regex to ensure it always allows deleting to the beginning of the line.
> Fix option-backspace behavior

- bpython/cli.py
- bpython/urwid.py
fixes #701 
Make it clear with comments that self.stdout_hist is bytes in Python 2, unicode in Python 3. Blech, would be nice to fix that to be unicode everywhere.
To debug I made self.stdout_hist a type-checking property, maybe this is worth doing for real? Also maybe static typechecking would be nice? But this PR just fixes this bug.
> fix encoding issues in urwid and curses

- bpython/cli.py
Currently, running `bpython-curses -i file.py` results in:
```
...
File ".local/share/virtualenvs/flask-ex-03Wix3mp/lib/python3.6/site-packages/bpython/cli.py", line 1905, in main_curses
bpython.args.exec_code(interpreter, args)
NameError: name 'bpython' is not defined
```
This PR addresses this error by correctly importing args and using it,
like the curtsies implementation.
> Fix bpython-curses bug when passed an argument

- .travis.yml
Currently, all the python3.7 tests fail on travis because of https://github.com/travis-ci/travis-ci/issues/9069. I adjusted .travis.yml as recommended by TravisCI developer BanzaiMan in https://github.com/travis-ci/travis-ci/issues/9069#issuecomment-425720905.
> Travis workaround to enable CI with python3.7

- bpython/curtsiesfrontend/repl.py
- bpython/test/test_curtsies_repl.py
Fixes #744.
I basically reverted #686 and merged the stdout and stderr formatting methods.
> Merge send_to_stdout and send_to_stderr; fix newline handling (#744)

- bpython/curtsiesfrontend/coderunner.py
Seems that this is a tuple unpacking issue. Let me know if this doesn't look right.
See these issues for more:
https://github.com/bpython/bpython/issues/722
https://github.com/bpython/bpython/issues/761
> Fix exit code issue

- bpython/inspection.py
This patch changes it so that `inspect.signature` is used instead of
`inspect.getfullargspec` to get a function's signature, when using Python 3.
Python 3.3 introduced the `inspect.signature` function as a new way to get the
signature of a function (as an alternative to `inspect.getargspec` and
`inspect.getfullargspec`).  `inspect.signature` has the advantage that it
preserves the signature of a decorated function if `functools.wraps` is used to
decorated the wrapper function.  Having a function's signature available is very
hepful, especially when testing things out in a REPL.
The below images show the change in action (first the old behavior, then the new one):
I was only able to test the changes on Python 3.7.2, but since all used functionality is available since Python 3.3 (and I only …
> Display the correct signature for a decorated function in Python 3

- bpython/config.py
I just lost a useful function I wrote that I hoped I could find in the history file.
a **utf-8** encoded history file having 1000 lines of code _less_ that 80 columns/characters long _less_ than 1000 * 80* **1** /1000=**~80** kilobytes in size.
or is the concern more about the look up time for autocomplete and the responsiveness of typing?
> 10x the too low hist_length default of 100 to 1000

- bpython/test/test_history.py
I divided the changes from #781 into two branches. This is the additional test case that I branched into `test-hist-file`.
> Add test case for accessing the history file

- bpython/curtsiesfrontend/repl.py
Fix issue #807 that I've opened.
The bug is as follows:
Some new python3.8 compatible packages are using the new importlib.metadata package instead of the now-old pkg_resources.
it has a new api, and it breaks inside bpython if "self.watcher" isn't None.
(Frankly I didn't invest the time to look what this "self.watcher" is.
I've just added the required api functionality for the imports to work.
> Support packages that are using the new importlib.metadata api

- README.rst
Link to http://bpython-interpreter.org. Same as homepage which appears earlier in the README.rst
> Fix project homepage link

- bpython/curtsiesfrontend/repl.py
Made small change in repl.py -- self.reevaluate(new_code=False) rather than True now.
> Don't pollute history with duplicate entries during reload-and-clear-modules

- bpython/curtsiesfrontend/repl.py
- setup.py
This addresses issue #749. It should now be fixed for normal input as well as stdin input.
Before:
After:
Also, because the issue with width aware text wrapping still exists (#731), it gets a little weird when you exceed one line. Still, I think the cursor is in the correct spot. In the below example the un-wrapped part is '６７８９０'. The cursor seems right despite the text not wrapping.
> Corrected cursor positioning on inputs with full-width (2 column) characters

- bpython/curtsiesfrontend/repl.py
- bpython/repl.py
- bpython/test/test_curtsies_repl.py
This is a working fix to #727, where long lines sent to the editor (usually with F7) are cut off and can't be edited correctly.
From what I can tell, the solution seems to work fine, but since this is the most code I've written at once for bpython, I want to make sure the structure / conventions / methods are valid. So I'll start it as a draft.
> Fix long lines sent to editor

- bpython/curtsiesfrontend/repl.py
The absence of `ImportFinder` wrapping the `find_spec` method (introduced in Python 3.4), which is a successor to now deprecated `find_module` [0] cause one of the finder classes to not find the namespace package, as it is only detectable using `find_spec`
Implements backwards-compatible logic to support `find_spec` if present in the Finder being wrapped.
Closes #835.
[0] https://docs.python.org/3/library/importlib.html#importlib.abc.MetaPathFinder.find_spec
> ImportFinder: Support find_spec interface

- bpython/curtsiesfrontend/repl.py
- bpython/repl.py
Small fix on a issue returning from editor which occurs after some changes I made to the commenting style on my last commit.
Side note: is it fine that some non-input lines in the editor session start with "# OUT:" and others with "### "? I think it's helpful for clarity, but I recognize that having the same prefix for all line is consistent.
> Fix issue returning from editor

- bpython/autocomplete.py
- bpython/inspection.py
- bpython/simpleeval.py
- bpython/test/test_autocomplete.py
- bpython/test/test_inspection.py
- bpython/test/test_simpleeval.py
I wanted to add open parenthesis completion in the suggestion box for callable functions, and I noticed there's some code we can consolidate or remove thanks to python3's `getattr_static` function. #163 mentions this. Here's what I changed.
- Start using getattr_static to avoid using AttrCleaner
- Refactor `safe_get_attribute` and `safe_get_attribute_new_style` from simpleeval.py, into `get_attr_safe` in inspection.py and move the tests from test_simpleeval to test_inspection
- Also add `has_attr_safe` to inspection.py
- Add some tests for has_attr_safe
Once we drop python 2 support, we can delete the python2 definition for `get_attr_safe` at which point AttrCleaner will be hardly used anywhere and can be removed / lightened up.
> Refactoring to start using getattr_static

- setup.py
Update minimum curtsies from 0.1.18 to 0.3.0 in preparation for introducing width awareness (my next PR).
I'm opening this as a separate PR just to confirm upgrading the version isn't what might bring runtime issues (something which was a concern with #731), and in case we don't end up accepting my next PR.
To start, I found no noticeably difference in runtime between curtsies 0.1.18 and 0.3.0 when printing, pasting, and moving my cursor around on long lines (1,000 to 10,000 chars).
> bump required curtsies version to 0.3.0

- bpython/cli.py
- bpython/repl.py
- bpython/urwid.py
Via issue #811, it was unclear what exactly s_hist is and where it's used. As I mention in that thread, s_hist stores inputs and outputs formatted as old formatstrings (with \x01 \x02 \x03 and \x04). It's used by cli.py to recreate the screen on screen resize.
With this PR, I
- rename s_hist to screen_hist to be more clear about it's purpose (is this fine?)
- added some comments to clarify things
- remove unused modifications to s_hist in urwid.py
> small refactor to s_hist

- bpython/curtsiesfrontend/repl.py
- bpython/curtsiesfrontend/replpainter.py
- bpython/test/test_curtsies_painting.py
This is a redux of #731 which was put on hold until a need for width awareness was found. I'd say this is a decent justification for bringing it back 
**Wrapping strings with fullwidth chars** 
Here's the same string being typed before and after width awareness:
**New method to fix cursor position:**
When we put a 2-column character at the end of the line where there's only 1 column of room, curtsies adds a padding character (space) so we can kick it down to the line below. Therefore, in order to get the right cursor position, I had to add a method that determines how many padding chars there are (`number_of_padding_chars_on_current_cursor_line`). 
Note on this method: Right now, to determine the amount of padding, it calls `display_linize`, doubling the amount of times we call that …
> Add width awareness to fix wrapping of strings with full width chars

- bpython/curtsiesfrontend/coderunner.py
- bpython/curtsiesfrontend/repl.py
- bpython/test/test_curtsies_coderunner.py
I propose we provide `fileno()` methods and `.encoding` properties on fake file objects that replace sys.stdin/stdout/stderr. Applications may use them in ways that work or in ways that don't, but we should just provide them and see what happens.
Pro: users can use more libraries with bpython
Con: code may break in less expected ways that the straightforward attribute errors they break on now, e.g. the display may break when a program writes directly to sys.stdout.fileno() because that won't be caught by bpython
> Fix fd encodings

- bpython/cli.py
- bpython/line.py
Two of these come from 0259cf8 and I'm not sure what the original intent was of checking for a curses key code like "\S" or "\T". I'm guessing they should be ^S and ^T, but ^S is usually already used for save. I'm going to remove these.
> Fix invalid escape sequences.

- doc/sphinx/source/configuration.rst
Fixing correct default directory for bpython config file (especially useful for color customization).
> Docs state wrong default config file directory

- requirements.txt
https://github.com/bpython/curtsies/pull/111 fixed an issue that causes a crash in mypy, but bpython isn't guaranteed to use a version of curtsies that includes this fix. this diff upgrades the bpython dependency on curtsies to 0.3.3, the latest release.
i couldn't find a contributing.md or similar to show how to build and test the diff, or with any other guidelines for contributors, so if there are additional steps i should take before this is shippable, please let me know!
> upgrading curtsies version to include changes from PR 111 to fix typing bug

- bpython/test/test.config
- bpython/test/test_crashers.py
Answer the cursor query and remove other output to simplify crasher tests for Curtsies.
> Enable crashers tests for Curtsies

- bpython/curtsies.py
Not undo!
```
TypeError: callback() takes 0 positional arguments but 1 was given
```
> Use kwarg for request_undo_callback to fix undo.

- bpython/test/test_inspection.py
- bpython/test/test_interpreter.py
- bpython/test/test_repl.py
Get pypy green again so we notice if something new breaks, by
- updating position of a ^ in a syntax error
- not using `range()` or `map()` for completion tests because pypy lacks signatures in its pydoc for some builtins, including these two
> disable some tests for pypy

- bpython/curtsiesfrontend/repl.py
There is a small typo in bpython/curtsiesfrontend/repl.py.
Should read `blocked` rather than `blockied`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: fix simple typo, blockied -> blocked

- bpython/curtsies.py
- bpython/curtsiesfrontend/repl.py
The module loading process has changed a lot (dropping support for 3.4 helps here), now auto-reloading works for me again.
> Fix watchdog auto-reloading

- doc/sphinx/source/contributing.rst
Hi! I was following the "contributing" documentation, but ran into an issue with a bad package version when setting up the project locally. I realized that `git describe --tags --first-parent` wasn't returning anything because I forked the repo without any of the tags.
<details>
<summary>For reference, here's the error I got when running `pip install -e .`</summary>
```
~/development/bpython (main*) » pip install -e .
---
Obtaining file:///home/nitant/development/bpython
Installing build dependencies ... done
Checking if build backend supports build_editable ... done
Getting requirements to build editable ... error
error: subprocess-exited-with-error
× Getting requirements to build editable did not run successfully.
│ exit code: 1
╰─> [55 lines of output]
running egg_info …
```
> Clarify fork instructions in contributing docs

- setup.cfg
The README, being a reStructuredText document, is not rendered as such on PyPI, just as plaintext – at least for releases [0.24](https://pypi.org/project/bpython/0.24/) and [0.23](https://pypi.org/project/bpython/0.23/), but not [0.22](https://pypi.org/project/bpython/0.22/).
I don't know exactly why that is; I *think* the default should already be reStructuredText. Maybe it's an older version of setuptools being used; or that all of `pyproject.toml`, `setup.cfg`, and `setup.py` are present and that results in some issue.
But given that `setup.cfg` is the one that is really considered, this change *should* fix that.
> Explicitly set README content type

- bpython/inspection.py
- bpython/test/test_repl.py
Followup to https://github.com/bpython/bpython/pull/932. I missed an edge-case :(
If a class uses exotic `__signature__` typings, but also has a `__file__` (that `inspect.getsourcelines` finds), then it is ignored whenever `_fix_default_values` doesn't work. In this case it should just 'trust' the `__signature__`.
> Fix __signature__ support if object has a __file__

- bpython/inspection.py
Autocompletions aren't supported for libraries (e.g. [Python.NET](https://github.com/pythonnet/pythonnet)) raising `AttributeError` when `setattr` is unsupported.
This PR fixes this by catching `AttributeError` alongside `TypeError`.
> inspection: handle AttributeError exceptions

- bpython/__init__.py
- bpython/keys.py
- bpython/lazyre.py
Added some functions return typing for the following files, helping with the #892 issue:
- `bpython/__init__.py`
- `bpython/keys.py`
- `bpython/lazyre.py`
> Added functions return typing in some files: __init__.py; keys.py and lazyre.py

- doc/sphinx/source/simplerepl.py
Default value was dropped in 8d16a71ef404db66d2c6fae6c362640da8ae240d
> Fix simplerepl demo: missing arg for BaseRepl init

- pyproject.toml
- requirements.txt
- setup.py
Closes #1014.
This PR proposes 2 changes:
- Import `build` from setuptools (motivation in #1014)
- Avoid patching of a class attribute of a class that owned by the project (`build.sub_commands`).
> Update `setup.py` for more up-to-date/robust customisation of the `build` command

- bpython/repl.py
Python 3.13's code.InteractiveInterpreter adds a new **kwargs argument to its showsyntaxerror() method. Currently, the only use of it is to send a named argument of name "source". Whilst the current adapation of repl.Interpreter is specific and should work in the short term, here is a more general solution.
> More general adaptation of showsyntaxerror() to Python 3.13

- setup.cfg
Should be picked up by PyPI and others.
Currently, bpython appears in PyPI search results with a description of "None".
> Add short project description
